[package]
name = "jsonrpc_proc_macro"
version = "0.1.0"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.26", features = ["full"] }
proc-macro2 = "0.4.26"
quote = "0.6.11"

