[package]
name = "jsonrpc"
version = "0.1.0"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"

[dependencies]
jsonrpc-core = "~8.0"
jsonrpc_proc_macro = { path = "../jsonrpc_proc_macro" }
serde_json = "1"
syn = "0.15.26"
